id: P005629
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC424
  title: 'ལོ་ཆེན་རིན་ཆེན་བཟང་པོའི་མཛད་འཕྲིན་ཞིབ་མོ་རྣམ་འབྱེད། '
  author: ''
  volumes:
    0ac3c1d459bc4e06a9fe2b07d3c1d435:
      image_group_id: I2PD18273
      title: ''
      volume_number: 1
      total_pages: 250
      base_file: v001.txt
