id: I52F54BB4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T01:05:25+00:00'
last_modified: '2022-06-08T05:24:54.735852+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC424
  title: 'ལོ་ཆེན་རིན་ཆེན་བཟང་པོའི་མཛད་འཕྲིན་ཞིབ་མོ་རྣམ་འབྱེད། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    3B48:
      image_group_id: I2PD18273
      title: ''
      total_pages: 250
      order: 1
      base_file: 3B48.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
